### ISSUE TITLE
Yarn Format duplicates the Copyright comment on Windows

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/liferay-npm-tools#207] opened 2019-08-21 13:21 UTC
When running `yarn format` or `yarn checkFormat` on Windows the output is unexpected.

In the case of `yarn format` the formatter will append the 13 lines of Copyright comment under the already existing one.

In the case of `yarn checkFormat` the output is following:
```
$ yarn checkFormat
yarn run v1.15.2
warning package.json: No license field
$ liferay-npm-scripts check
src/main/resources/META-INF/resources/index.es.js: BAD
src/main/resources/META-INF/resources/liferay/aop/AOP.es.js: BAD
src/main/resources/META-INF/resources/liferay/compat/modal/Modal.es.js: BAD
src/main/resources/META-INF/resources/liferay/compat/progressbar/ProgressBar.es.js: BAD
src/main/resources/META-INF/resources/liferay/compat/slider/Slider.es.js: BAD
src/main/resources/META-INF/resources/liferay/compat/treeview/Treeview.es.js: BAD
src/main/resources/META-INF/resources/liferay/CompatibilityEventProxy.es.js: BAD
src/main/resources/META-INF/resources/liferay/component.es.js: BAD
src/main/resources/META-INF/resources/liferay/debounce/debounce.es.js: BAD
src/main/resources/META-INF/resources/liferay/DefaultEventHandler.es.js: BAD
src/main/resources/META-INF/resources/liferay/dom_task_runner.js: BAD
src/main/resources/META-INF/resources/liferay/DynamicInlineScroll.es.js: BAD
src/main/resources/META-INF/resources/liferay/events.js: BAD
src/main/resources/META-INF/resources/liferay/global.es.js: BAD
src/main/resources/META-INF/resources/liferay/ItemSelectorDialog.es.js: BAD
src/main/resources/META-INF/resources/liferay/keyboard-focus/KeyboardFocusManager.es.js: BAD
src/main/resources/META-INF/resources/liferay/layout_exporter.js: BAD
src/main/resources/META-INF/resources/liferay/lazy_load.js: BAD
src/main/resources/META-INF/resources/liferay/liferay.js: BAD
src/main/resources/META-INF/resources/liferay/modal/commands/OpenSimpleInputModal.es.js: BAD
src/main/resources/META-INF/resources/liferay/modal/components/SimpleInputModal.es.js: BAD
src/main/resources/META-INF/resources/liferay/portal.js: BAD
src/main/resources/META-INF/resources/liferay/portlet/portlet.es.js: BAD
src/main/resources/META-INF/resources/liferay/portlet/PortletInit.es.js: BAD
src/main/resources/META-INF/resources/liferay/portlet/portlet_constants.es.js: BAD
src/main/resources/META-INF/resources/liferay/portlet/portlet_util.es.js: BAD
src/main/resources/META-INF/resources/liferay/portlet/register.es.js: BAD
src/main/resources/META-INF/resources/liferay/portlet/RenderState.es.js: BAD
src/main/resources/META-INF/resources/liferay/portlet.js: BAD
src/main/resources/META-INF/resources/liferay/PortletBase.es.js: BAD
src/main/resources/META-INF/resources/liferay/side_navigation.es.js: BAD
src/main/resources/META-INF/resources/liferay/toast/commands/OpenToast.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/address/get_countries.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/address/get_regions.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/fetch.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/form/get_form_element.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/form/object_to_form_data.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/form/post_form.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/form/set_form_values.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/format_storage.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/format_xml.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/get_crop_region.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/get_portlet_namespace.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/navigate.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/ns.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/object_to_url_search_params.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/portlet_url/create_action_url.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/portlet_url/create_portlet_url.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/portlet_url/create_render_url.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/portlet_url/create_resource_url.es.js: BAD
src/main/resources/META-INF/resources/liferay/util/to_char_code.es.js: BAD
src/main/resources/META-INF/resources/liferay/workflow.js: BAD
src/main/resources/META-INF/resources/loader/config.js: BAD
src/main/resources/META-INF/resources/misc/swfobject.js: BAD
src/main/resources/META-INF/resources/misc/xp_progress.js: BAD
test/liferay/aop/AOP.es.js: BAD
test/liferay/CompatibilityEventProxy.es.js: BAD
test/liferay/component.es.js: BAD
test/liferay/debounce/debounce.es.js: BAD
test/liferay/keyboard-focus/KeyboardFocusManager.es.js: BAD
test/liferay/portlet/action.es.js: BAD
test/liferay/portlet/create_resource_url.es.js: BAD
test/liferay/portlet/events.es.js: BAD
test/liferay/portlet/in_progress.es.js: BAD
test/liferay/portlet/mock/portlet_data.es.js: BAD
test/liferay/portlet/mock/setup.es.js: BAD
test/liferay/portlet/register.es.js: BAD
test/liferay/portlet/state.es.js: BAD
test/liferay/PortletBase.es.js: BAD
test/liferay/util/address/get_countries.es.js: BAD
test/liferay/util/address/get_regions.es.js: BAD
test/liferay/util/fetch.es.js: BAD
test/liferay/util/form/get_form_element.es.js: BAD
test/liferay/util/form/object_to_form_data.es.js: BAD
test/liferay/util/form/post_form.es.js: BAD
test/liferay/util/form/set_form_values.es.js: BAD
test/liferay/util/format_storage.es.js: BAD
test/liferay/util/format_xml.es.js: BAD
test/liferay/util/get_crop_region.es.js: BAD
test/liferay/util/get_portlet_namespace.es.js: BAD
test/liferay/util/mock/headers.es.js: BAD
test/liferay/util/mock/setup.es.js: BAD
test/liferay/util/navigate.es.js: BAD
test/liferay/util/ns.es.js: BAD
test/liferay/util/object_to_url_search_params.es.js: BAD
test/liferay/util/portlet_url/create_action_url.es.js: BAD
test/liferay/util/portlet_url/create_portlet_url.es.js: BAD
test/liferay/util/portlet_url/create_render_url.es.js: BAD
test/liferay/util/portlet_url/create_resource_url.es.js: BAD
test/liferay/util/to_char_code.es.js: BAD
Prettier checked 90 files, 90 files have problems
```

**Comment by wincent** [comment] 2019-08-21 14:07
@kresimir-coko: can you post a gist of the actual changes it makes?

One thing I notice is that it is Prettier that is complaining about bad formatting (which makes me think something about line-endings, or the final trailing newline in the files), but the thing which inserts "missing" copyright headers is ESLint. I don't see any output from ESLint in what you pasted; is there more?

**Comment by kresimir-coko** [comment] 2019-08-22 07:23
@wincent Here you go https://gist.github.com/kresimir-coko/73a5ec52f3499f7dcea5e45fcc1816e9

It's the same outcome for any `*.js` or `*.es.js` file

**Comment by wincent** [comment] 2019-08-22 08:18
Thanks @kresimir-coko. Looking at the raw bytes I can only see `0x0a` (ie. newlines), not `0x0d` (ie. carriage returns), so that's not it. Will have to try and repro it on the Window lappy here.

What about my other question?

> the thing which inserts "missing" copyright headers is ESLint. I don't see any output from ESLint in what you pasted; is there more?

**Comment by wincent** [comment] 2019-08-22 08:20
Another doubt I have is whether you have any local configuration related to line endings that might be obscuring what's really happening (for example, the stuff [in here](https://help.github.com/en/articles/configuring-git-to-handle-line-endings)).

**Comment by kresimir-coko** [comment] 2019-08-22 08:34
Don't know why I omitted this part of the output when running `yarn checkFormat`. But here is the final few lines.

```
ESLint checked 79 files, found 0 errors, found 0 warnings
1 of 2 jobs failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kresimir-coko** [comment] 2019-08-22 09:00
Good luck! 🗡 🗡 🗡

**Comment by wincent** [comment] 2019-09-13 09:44
Is this still happening for you @kresimir-coko?

I tried reproducing this on the Windows laptop here to no avail. Doesn't change any files when run from the top-level "modules/" folder, or from a subproject like "frontend-js-web".

**Comment by wincent** [comment] 2019-09-13 21:08
It's possible that you might have some transparent line-ending conversion going on in Git whenever you checkout. Which in turn means that [this commit](https://github.com/liferay/liferay-npm-tools/pull/248/commits/5ca2873a6d9dadf8f66cd4e0b359a058a17d2515) just might fix it (on an unrelated PR). Just in case that one gets force-pushed and goes away, this is it:

```
From 5ca2873a6d9dadf8f66cd4e0b359a058a17d2515 Mon Sep 17 00:00:00 2001
From: Greg Hurrell <greg@hurrell.net>
Date: Fri, 13 Sep 2019 22:58:01 +0200
Subject: [PATCH] fix: add a .gitattributes file to unbreak Travis on Windows

My suspicion is that when Travis does its Git checkout, it converts all
LF to CRLF, and that breaks the snapshots because all the indices
change; example:

https://travis-ci.org/liferay/liferay-npm-tools/jobs/584751075

See:

- https://help.github.com/en/articles/configuring-git-to-handle-line-endings
- https://git-scm.com/docs/gitattributes
---
 .gitattributes | 6 ++++++
 1 file changed, 6 insertions(+)
 create mode 100644 .gitattributes

diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 0000000..b4195e7
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1,6 @@
+# Don't let Git transform line-endings to CRLF on Windows, because that
+# would break the snapshots.
+*.js text eol=lf
+*.jsp text eol=lf
+*.jspf text eol=lf
+*.js.snap text eol=lf
-- 
2.20.1
```

**Comment by jbalsas** [comment] 2019-09-16 08:46
I was going to say this was not possible because we already had a `.gitattributes` in place at [liferay-portal/.gitattributes](https://github.com/liferay/liferay-portal/blob/master/.gitattributes) but it turns out it's only for `pom` and `ivy.xml` files. 

We used to apply it for `soy` files when the Soy Compiler had trouble with line endings in windows, but that [got fixed by the compiler itself](https://github.com/liferay/liferay-portal/commit/c73cb4f96089ba81958adf849ae7d2291273fb67), so maybe this is also something that can be taken care of somewhere else?

**Comment by wincent** [comment] 2019-09-17 07:42
There are two "somewhere elses" apart from an actual `.gitattributes` file that I can think of: one is inside [eslint-plugin-notice](https://www.npmjs.com/package/eslint-plugin-notice) (which we don't control, although we might be able to submit a PR) and the other is via `git config` like I said above (which isn't ideal because every Windows developer would have to do it).

I guess the other thing we could do is something hacky like dynamically detect when running on windows and pass an alternate `templateFile` path to eslint-plugin-notice; we could construct that template file on the fly by converting the line-endings and writing out a new file to a temporary location.

Still, I'm curious to know why I couldn't repro on the Windows laptop. Maybe because I was using the fancy shell that gets installed with Git.

**Comment by wincent** [comment] 2020-01-21 14:14
Given that we don't have a reliable repro, I am going to close this as non-actionable. If somebody can provide repro steps that work, we'll reopen.

**Closed by wincent** 2020-01-21 14:14 UTC
Labels: bug, windows
